services:
  postgres:
    image: postgres:17-alpine
    container_name: cinema-functions-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: cinema_functions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - cinema_functions_data:/var/lib/postgresql/data

volumes:
  cinema_functions_data: